### PR TITLE
chore: fix rpc port config

### PR DESCRIPTION
**Pull request by KanishkKhurana**
## Why?

minor port fix based on discussion

## How?

remove DHT port and add pinger port

### CODE REVIEW

**Review by matthias-wright — APPROVED** [review]
LGTM

**Comment by matthias-wright** [comment]
just realized the title says rpc port, but the rpc port wasn't changed. were you planning on changing the rpc port to the current testnet port?

**Comment by KanishkKhurana** [comment]
> just realized the title says rpc port, but the rpc port wasn't changed. were you planning on changing the rpc port to the current testnet port?

Thanks for pointing that out. I have added the change here

**Review by matthias-wright — APPROVED** [review]
LGTM

**Pull request merged**
